### ISSUE TITLE
Everything Blue Glow

### ISSUE THREAD

**Issue by branson925** [AdiAddons/AdiBags#879]
### Addon Version

1.9.53

### World of Warcraft Version

Wrath

### Describe the bug

Every item now has a blue glow around it. How do I change it? Only happened since new update today.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/122075850/210936098-f931ff21-2c98-4d19-90b8-a4896de083ab.png)

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by HolteUnderscore** [comment]
Getting exactly the same, just to confirm.
Have gone back to 1.9.52 in lieu of fix.

**Comment by Cidan** [comment]
Huh. Someone else reported this, but only on PTR. I am able to reproduce it, but I have no idea what's causing it. Will work on it.

**Comment by rdragan** [comment]
@Cidan It's the `BattlepayItemTexture`, seems it's shown by default and #878 made it only hide on retail.

**Comment by Cidan** [comment]
@rdragan I was literally just playing with my dog and it suddenly hit me that this was the issue, hah, I'll get a fix out!

**Comment by Cidan** [comment]
Fixed with 1.9.54, out in a few minutes. Thanks everyone!

**Comment by branson925** [comment]
Appreciate you!

**Comment by jpunlimited** [comment]
Hi, issue is still occuring on the classic era version. Thanks
