### ISSUE TITLE
[PTR] attempt to call upvalue 'IsBattlePayItem' 

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#883]
### Addon Version

v1.9.54

### World of Warcraft Version

WOTLK Classic PTR

### Describe the bug

Not sure if this has been reported yet or not. I'm not seeing the blue outlines anymore but I am seeing this bug consistently
 
```
32x Interface/AddOns/AdiBags/modules/NewItemTracking.lua:165: attempt to call upvalue 'IsBattlePayItem' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Filters.lua"]:146: in function `Filter'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:827: in function `FilterSlot'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:861: in function `DispatchItem'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1031: in function `RedispatchAllItems'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1189: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:1172>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:509: in function `RefreshContents'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:494: in function `ResumeUpdates'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:474: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:466>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:96: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:217: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/core/Core.lua"]:459: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?
```

### Steps to reproduce

Open bag and mouseover stuff

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Oh interesting, these UI changes seem to be live in WotLK and Classic already. Thanks, I'll get this fixed for retail PTR.

**Comment by Jakobud** [comment]
Oh sorry the dropdown I picked the wrong one. This was WOTLK Classic PTR!

**Comment by Cidan** [comment]
Are you on the latest version? This should be fixed on it.

**Comment by Jakobud** [comment]
I just tried v1.10.0 release from the repo and unfortunately still the same result:

![image](https://user-images.githubusercontent.com/87356/211243252-0cf2cabc-0472-4c2c-b436-910d2935f95f.png)

![image](https://user-images.githubusercontent.com/87356/211243288-b657d1ad-8588-4ad7-904e-9b450950f195.png)

**Comment by Jakobud** [comment]
It's playable on the PTR it just happens a lot when you are opening your bags or looting stuff or using items in your bags.

Is there anything specific I can do to help you recreate the issue or help you pinpoint the issue?

**Comment by Cidan** [comment]
Ah, I found it the issue. I'll put a fix out with 1.10.1. Thanks :)

**Comment by Jakobud** [comment]
Rock on. I love this addon. Best bag addon hands down. I'll always submit bug reports when I find em :)

**Comment by Cidan** [comment]
Thanks! Hopefully the new theme system and Masque support works well. I use GW2 UI, and being able to have a set theme for it with Masque has been great:
![image](https://user-images.githubusercontent.com/1133628/211244042-cb5c3bea-1a4b-4622-88c7-1d243d017f25.png)
